### PR TITLE
Only display landing page on /

### LINKED ISSUE #241: response 200 when url is incorrect
### Host operating system: output of `uname -a`
Darwin Kernel Version 24.0.0: Mon Aug 12 21:27:44 PDT 2024; root:xnu-11215.1.10~5/RELEASE_ARM64_T8103 arm64

### node_exporter version: output of `node_exporter --version`

node_exporter, version 1.8.2 (branch: HEAD, revision: f1e0e8360aa60b6cb5e5cc1560bed348fc2c1895)

### node_exporter command line flags

./node_exporter

### Are you running node_exporter in Docker?

no

### What did you do that produced an error?
➜  ~ curl -Iv http://127.0.0.1:9100/tes
*   Trying 127.0.0.1:9100...
* Connected to 127.0.0.1 (127.0.0.1) port 9100
> HEAD /tes HTTP/1.1
> Host: 127.0.0.1:9100
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Date: Thu, 29 Aug 2024 09:41:39 GMT
Date: Thu, 29 Aug 2024 09:41:39 GMT
< Content-Length: 961
Content-Length: 961

### What did you expect to see?
http return 404

### What did you see instead?
 HTTP returns a 200 status code, which is unusual.

### PR DESCRIPTION
**Pull request by schoentoon**
This would fix #241 we ran into this issue when some of our automated tests fully believed that node exporter was leaking a linux home directory as it was returning HTTP 200 on requests like .bash_history

### CODE REVIEW

File: web/landing_page.go [hunk 1]
```diff
@@ -106,6 +106,11 @@ func NewLandingPage(c LandingConfig) (*LandingPageHandler, error) {
 }
 
 func (h *LandingPageHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
+	if r.URL.Path != "/" {
+		w.Write([]byte("Not Found"))
+		w.WriteHeader(http.StatusNotFound)
```
Comment (SuperQ) [inline web/landing_page.go:111]:
```suggestion
		http.NotFound(w, r)
```

**Review by SuperQ — CHANGES_REQUESTED** [review]
Thanks! I just noticed this when I was working on https://github.com/prometheus/graphite_exporter/pull/278.

Minor simplification using the existing `net/http` function.

File: web/landing_page.go (hunk 1 above)
Comment (schoentoon) [reply web/landing_page.go]: Excellent point. I always forget about this helper function existing.

**Review by SuperQ — APPROVED** [review]
Thanks!
